
Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.hostname = "jenkins"
    jenkins.vm.network "private_network", ip: "192.168.33.10"
end
  config.vm.define "ansible" do |ansible|
    ansible.vm.hostname = "ansible"
    ansible.vm.network "private_network", ip: "192.168.33.11"
end
  config.vm.define "instance" do |instance|
    instance.vm.hostname = "instance"
    instance.vm.network "private_network", ip: "192.168.33.20"
end
  config.vm.define "docker" do |docker|
    docker.vm.hostname = "docker"
    docker.vm.network "private_network", ip: "192.168.33.21"
end
  config.vm.define "db" do |db|
    db.vm.hostname = "db"
    db.vm.network "private_network", ip: "192.168.33.30"
end

end
